from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Remove stack protector
#
bootstrap_env = env.Clone()
bootstrap_env['CCFLAGS'].remove('-fstack-protector-all')

#
# Dependencies
#
deps = ['keepkey_board']
project_deps += deps

init_project(bootstrap_env, 
    deps=deps, 
    libs=['opencm3_stm32f2'])