from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Remove stack protector
#
env = remove_flags(env, ['-fstack-protector-all'])

#
# Dependencies
#
deps = ['keepkey_board']
project_deps += deps

init_project(env, deps=deps, libs=['opencm3_stm32f2'])