#!/bin/bash
#
# Script used to setup and configure the keepkey workspace.
#
NORMAL="\e[0m"
GREEN="\e[92m"
RED="\e[91m"

#
# FIXME: move this out to a general manifest.
#
REPOS=(
       "git clone ssh://git@bitbucket.org/CarbonDesign/app"
       "git clone ssh://git@bitbucket.org/CarbonDesign/crypto"
       "git clone ssh://git@bitbucket.org/CarbonDesign/foundation"
       "git clone ssh://git@bitbucket.org/CarbonDesign/graphics_engine"
       "git clone ssh://git@bitbucket.org/CarbonDesign/hsm"
       "git clone ssh://git@bitbucket.org/CarbonDesign/site_scons"
       "git clone https://github.com/trezor/trezor-mcu.git" 
       )


# 
# Cloning out child project repos.
#
echo -e $GREEN"Cloning out child repos $NORMAL"

IFS=""
for repo in ${REPOS[*]}; do
   eval ${repo}
   if [[ $? -ne 0 ]]; then
      echo -e $RED"Error cloning out ${repo}.  Bailing out.$NORMAL"
      exit -1
   fi
done

echo -e $GREEN"Now run 'cd trezor-mcu && git submodule init && git submodule update'"$NORMAL

