from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Dependencies
#
deps = ['keepkey_board', 'interface', 'nanopb', 'crypto']
project_deps += deps

#
# Debug Link
#
if int(ARGUMENTS.get('debug_link', 0)):
    env = add_flags(env, ['-DDEBUG_LINK=1'])
else:
    env = add_flags(env, ['-DDEBUG_LINK=0'])

if(ARGUMENTS.get('project') == 'keepkey'):
    env = add_flags(env, ['-DKEEPKEY_PRJ'])

if(ARGUMENTS.get('salt-logo')):
    env = add_flags(env, ['-DSALT_WHITELABEL'])

if(ARGUMENTS.get('manufacturer')):
    env = add_flags(env, ['-DMANUFACTURER=1'])

init_project(env, deps=deps, libs=['opencm3_stm32f2'])

