from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Dependencies
#
deps = ["nanopb", "interface", "crypto"]
project_deps += deps

#
# Invert Display
#
if int(ARGUMENTS.get('invert', 0)):
  env = add_flags(env, ['-DINVERT_DISPLAY=1'])

#
# Debug Link
#
if int(ARGUMENTS.get('debug_link', 0)):
    env = add_flags(env, ['-DDEBUG_LINK=1'])
else:
    env = add_flags(env, ['-DDEBUG_LINK=0'])

if(ARGUMENTS.get('project') == 'keepkey'):
    env = add_flags(env, ['-DKEEPKEY_PRJ'])

init_project(env, deps=deps, libs=["opencm3_stm32f2"])
