/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9.2 at Thu Jun  2 16:36:37 2016. */

#ifndef _PB_EXCHANGE_PB_H_
#define _PB_EXCHANGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Exchange_Address {
    bool has_address;
    char address[36];
    bool has_dest_tag;
    char dest_tag[4];
    bool has_rs_address;
    char rs_address[4];
} Exchange_Address;

typedef struct _SendAmountRequest {
    bool has_withdrawal_amount;
    uint64_t withdrawal_amount;
    bool has_withdrawal_address;
    Exchange_Address withdrawal_address;
    bool has_withdrawal_coin_type;
    char withdrawal_coin_type[17];
    bool has_deposit_coin_type;
    char deposit_coin_type[17];
    bool has_return_address;
    Exchange_Address return_address;
    pb_callback_t api_key;
} SendAmountRequest;

typedef struct {
    size_t size;
    uint8_t bytes[73];
} SendAmountResponse_signature_t;

typedef struct _SendAmountResponse {
    bool has_signature;
    SendAmountResponse_signature_t signature;
    bool has_request;
    SendAmountRequest request;
    bool has_deposit_address;
    Exchange_Address deposit_address;
    bool has_deposit_amount;
    uint64_t deposit_amount;
    bool has_expiration;
    uint32_t expiration;
    bool has_quoted_rate;
    uint32_t quoted_rate;
} SendAmountResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Exchange_Address_init_default            {false, "", false, "", false, ""}
#define SendAmountRequest_init_default           {false, 0, false, Exchange_Address_init_default, false, "", false, "", false, Exchange_Address_init_default, {{NULL}, NULL}}
#define SendAmountResponse_init_default          {false, {0, {0}}, false, SendAmountRequest_init_default, false, Exchange_Address_init_default, false, 0, false, 0, false, 0}
#define Exchange_Address_init_zero               {false, "", false, "", false, ""}
#define SendAmountRequest_init_zero              {false, 0, false, Exchange_Address_init_zero, false, "", false, "", false, Exchange_Address_init_zero, {{NULL}, NULL}}
#define SendAmountResponse_init_zero             {false, {0, {0}}, false, SendAmountRequest_init_zero, false, Exchange_Address_init_zero, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Exchange_Address_address_tag             1
#define Exchange_Address_dest_tag_tag            2
#define Exchange_Address_rs_address_tag          3
#define SendAmountRequest_withdrawal_amount_tag  1
#define SendAmountRequest_withdrawal_address_tag 2
#define SendAmountRequest_withdrawal_coin_type_tag 3
#define SendAmountRequest_deposit_coin_type_tag  4
#define SendAmountRequest_return_address_tag     5
#define SendAmountRequest_api_key_tag            6
#define SendAmountResponse_signature_tag         1
#define SendAmountResponse_request_tag           2
#define SendAmountResponse_deposit_address_tag   3
#define SendAmountResponse_deposit_amount_tag    4
#define SendAmountResponse_expiration_tag        5
#define SendAmountResponse_quoted_rate_tag       6

/* Struct field encoding specification for nanopb */
extern const pb_field_t Exchange_Address_fields[4];
extern const pb_field_t SendAmountRequest_fields[7];
extern const pb_field_t SendAmountResponse_fields[7];

/* Maximum encoded size of messages (where known) */
#define Exchange_Address_size                    50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
