/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9.2 at Thu Dec 21 23:32:46 2017. */

#ifndef _PB_EXCHANGE_PB_H_
#define _PB_EXCHANGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _ExchangeAddress {
    bool has_coin_type;
    char coin_type[17];
    bool has_address;
    char address[43];
    bool has_dest_tag;
    char dest_tag[4];
    bool has_rs_address;
    char rs_address[43];
} ExchangeAddress;

typedef struct {
    size_t size;
    uint8_t bytes[64];
} ExchangeResponse_api_key_t;

typedef struct {
    size_t size;
    uint8_t bytes[18];
} ExchangeResponse_order_id_t;

typedef struct _ExchangeResponse {
    bool has_deposit_address;
    ExchangeAddress deposit_address;
    bool has_deposit_amount;
    uint64_t deposit_amount;
    bool has_expiration;
    int64_t expiration;
    bool has_quoted_rate;
    uint64_t quoted_rate;
    bool has_withdrawal_address;
    ExchangeAddress withdrawal_address;
    bool has_withdrawal_amount;
    uint64_t withdrawal_amount;
    bool has_return_address;
    ExchangeAddress return_address;
    bool has_api_key;
    ExchangeResponse_api_key_t api_key;
    bool has_miner_fee;
    uint64_t miner_fee;
    bool has_order_id;
    ExchangeResponse_order_id_t order_id;
} ExchangeResponse;

typedef struct {
    size_t size;
    uint8_t bytes[32];
} ExchangeResponseV2_deposit_amount_t;

typedef struct {
    size_t size;
    uint8_t bytes[32];
} ExchangeResponseV2_quoted_rate_t;

typedef struct {
    size_t size;
    uint8_t bytes[32];
} ExchangeResponseV2_withdrawal_amount_t;

typedef struct {
    size_t size;
    uint8_t bytes[64];
} ExchangeResponseV2_api_key_t;

typedef struct {
    size_t size;
    uint8_t bytes[32];
} ExchangeResponseV2_miner_fee_t;

typedef struct {
    size_t size;
    uint8_t bytes[18];
} ExchangeResponseV2_order_id_t;

typedef struct _ExchangeResponseV2 {
    bool has_deposit_address;
    ExchangeAddress deposit_address;
    bool has_deposit_amount;
    ExchangeResponseV2_deposit_amount_t deposit_amount;
    bool has_expiration;
    int64_t expiration;
    bool has_quoted_rate;
    ExchangeResponseV2_quoted_rate_t quoted_rate;
    bool has_withdrawal_address;
    ExchangeAddress withdrawal_address;
    bool has_withdrawal_amount;
    ExchangeResponseV2_withdrawal_amount_t withdrawal_amount;
    bool has_return_address;
    ExchangeAddress return_address;
    bool has_api_key;
    ExchangeResponseV2_api_key_t api_key;
    bool has_miner_fee;
    ExchangeResponseV2_miner_fee_t miner_fee;
    bool has_order_id;
    ExchangeResponseV2_order_id_t order_id;
} ExchangeResponseV2;

typedef struct {
    size_t size;
    uint8_t bytes[65];
} SignedExchangeResponse_signature_t;

typedef struct _SignedExchangeResponse {
    bool has_response;
    ExchangeResponse response;
    bool has_signature;
    SignedExchangeResponse_signature_t signature;
    bool has_responseV2;
    ExchangeResponseV2 responseV2;
} SignedExchangeResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ExchangeAddress_init_default             {false, "", false, "", false, "", false, ""}
#define ExchangeResponseV2_init_default          {false, ExchangeAddress_init_default, false, {0, {0}}, false, 0, false, {0, {0}}, false, ExchangeAddress_init_default, false, {0, {0}}, false, ExchangeAddress_init_default, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define SignedExchangeResponse_init_default      {false, ExchangeResponse_init_default, false, {0, {0}}, false, ExchangeResponseV2_init_default}
#define ExchangeResponse_init_default            {false, ExchangeAddress_init_default, false, 0, false, 0, false, 0, false, ExchangeAddress_init_default, false, 0, false, ExchangeAddress_init_default, false, {0, {0}}, false, 0, false, {0, {0}}}
#define ExchangeAddress_init_zero                {false, "", false, "", false, "", false, ""}
#define ExchangeResponseV2_init_zero             {false, ExchangeAddress_init_zero, false, {0, {0}}, false, 0, false, {0, {0}}, false, ExchangeAddress_init_zero, false, {0, {0}}, false, ExchangeAddress_init_zero, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define SignedExchangeResponse_init_zero         {false, ExchangeResponse_init_zero, false, {0, {0}}, false, ExchangeResponseV2_init_zero}
#define ExchangeResponse_init_zero               {false, ExchangeAddress_init_zero, false, 0, false, 0, false, 0, false, ExchangeAddress_init_zero, false, 0, false, ExchangeAddress_init_zero, false, {0, {0}}, false, 0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define ExchangeAddress_coin_type_tag            1
#define ExchangeAddress_address_tag              2
#define ExchangeAddress_dest_tag_tag             3
#define ExchangeAddress_rs_address_tag           4
#define ExchangeResponse_deposit_address_tag     1
#define ExchangeResponse_deposit_amount_tag      2
#define ExchangeResponse_expiration_tag          3
#define ExchangeResponse_quoted_rate_tag         4
#define ExchangeResponse_withdrawal_address_tag  5
#define ExchangeResponse_withdrawal_amount_tag   6
#define ExchangeResponse_return_address_tag      7
#define ExchangeResponse_api_key_tag             8
#define ExchangeResponse_miner_fee_tag           9
#define ExchangeResponse_order_id_tag            10
#define ExchangeResponseV2_deposit_address_tag   1
#define ExchangeResponseV2_deposit_amount_tag    2
#define ExchangeResponseV2_expiration_tag        3
#define ExchangeResponseV2_quoted_rate_tag       4
#define ExchangeResponseV2_withdrawal_address_tag 5
#define ExchangeResponseV2_withdrawal_amount_tag 6
#define ExchangeResponseV2_return_address_tag    7
#define ExchangeResponseV2_api_key_tag           8
#define ExchangeResponseV2_miner_fee_tag         9
#define ExchangeResponseV2_order_id_tag          10
#define SignedExchangeResponse_response_tag      1
#define SignedExchangeResponse_signature_tag     2
#define SignedExchangeResponse_responseV2_tag    3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ExchangeAddress_fields[5];
extern const pb_field_t ExchangeResponseV2_fields[11];
extern const pb_field_t SignedExchangeResponse_fields[4];
extern const pb_field_t ExchangeResponse_fields[11];

/* Maximum encoded size of messages (where known) */
#define ExchangeAddress_size                     115
#define ExchangeResponseV2_size                  584
#define SignedExchangeResponse_size              1149
#define ExchangeResponse_size                    492

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
