/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9.2 at Mon Jun 27 18:32:31 2016. */

#ifndef _PB_EXCHANGE_PB_H_
#define _PB_EXCHANGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _ExchangeAddress {
    bool has_address;
    char address[36];
    bool has_dest_tag;
    char dest_tag[4];
    bool has_rs_address;
    char rs_address[36];
} ExchangeAddress;

typedef struct {
    size_t size;
    uint8_t bytes[4];
} ExchangeRequest_api_key_t;

typedef struct _ExchangeRequest {
    bool has_withdrawal_amount;
    uint64_t withdrawal_amount;
    bool has_withdrawal_address;
    ExchangeAddress withdrawal_address;
    bool has_withdrawal_coin_type;
    char withdrawal_coin_type[17];
    bool has_deposit_coin_type;
    char deposit_coin_type[17];
    bool has_return_address;
    ExchangeAddress return_address;
    bool has_api_key;
    ExchangeRequest_api_key_t api_key;
} ExchangeRequest;

typedef struct {
    size_t size;
    uint8_t bytes[65];
} ExchangeResponse_signature_t;

typedef struct _ExchangeResponse {
    bool has_request;
    ExchangeRequest request;
    bool has_deposit_address;
    ExchangeAddress deposit_address;
    bool has_deposit_amount;
    uint64_t deposit_amount;
    bool has_expiration;
    uint32_t expiration;
    bool has_quoted_rate;
    uint32_t quoted_rate;
    bool has_signature;
    ExchangeResponse_signature_t signature;
} ExchangeResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ExchangeAddress_init_default             {false, "", false, "", false, ""}
#define ExchangeRequest_init_default             {false, 0, false, ExchangeAddress_init_default, false, "", false, "", false, ExchangeAddress_init_default, false, {0, {0}}}
#define ExchangeResponse_init_default            {false, ExchangeRequest_init_default, false, ExchangeAddress_init_default, false, 0, false, 0, false, 0, false, {0, {0}}}
#define ExchangeAddress_init_zero                {false, "", false, "", false, ""}
#define ExchangeRequest_init_zero                {false, 0, false, ExchangeAddress_init_zero, false, "", false, "", false, ExchangeAddress_init_zero, false, {0, {0}}}
#define ExchangeResponse_init_zero               {false, ExchangeRequest_init_zero, false, ExchangeAddress_init_zero, false, 0, false, 0, false, 0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define ExchangeAddress_address_tag              1
#define ExchangeAddress_dest_tag_tag             2
#define ExchangeAddress_rs_address_tag           3
#define ExchangeRequest_withdrawal_amount_tag    1
#define ExchangeRequest_withdrawal_address_tag   2
#define ExchangeRequest_withdrawal_coin_type_tag 3
#define ExchangeRequest_deposit_coin_type_tag    4
#define ExchangeRequest_return_address_tag       5
#define ExchangeRequest_api_key_tag              6
#define ExchangeResponse_request_tag             1
#define ExchangeResponse_deposit_address_tag     2
#define ExchangeResponse_deposit_amount_tag      3
#define ExchangeResponse_expiration_tag          4
#define ExchangeResponse_quoted_rate_tag         5
#define ExchangeResponse_signature_tag           6

/* Struct field encoding specification for nanopb */
extern const pb_field_t ExchangeAddress_fields[4];
extern const pb_field_t ExchangeRequest_fields[7];
extern const pb_field_t ExchangeResponse_fields[7];

/* Maximum encoded size of messages (where known) */
#define ExchangeAddress_size                     82
#define ExchangeRequest_size                     223
#define ExchangeResponse_size                    400

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
