extern "C" {
#include "keepkey/firmware/zcash.h"
#include "trezor/crypto/bignum.h"
#include "trezor/crypto/blake2b.h"
#include "trezor/crypto/memzero.h"
#include "trezor/crypto/pallas.h"
#include "trezor/crypto/redpallas.h"
}

#include "gtest/gtest.h"
#include <cstring>

/* ── Pallas curve constants ──────────────────────────────────────── */

/* Pallas base field prime p (LE) */
static const uint8_t PALLAS_P_LE[32] = {
    0x01, 0x00, 0x00, 0x00, 0xed, 0x30, 0x2d, 0x99,
    0x1b, 0xf9, 0x4c, 0x09, 0xfc, 0x98, 0x46, 0x22,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
};

/* Pallas scalar field order q (LE) */
static const uint8_t PALLAS_Q_LE[32] = {
    0x01, 0x00, 0x00, 0x00, 0x21, 0xeb, 0x46, 0x8c,
    0xdd, 0xa8, 0x94, 0x09, 0xfc, 0x98, 0x46, 0x22,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40,
};

/* Compare two 32-byte LE values: return -1 if a < b, 0 if equal, 1 if a > b */
static int cmp_le256(const uint8_t a[32], const uint8_t b[32]) {
  for (int i = 31; i >= 0; i--) {
    if (a[i] < b[i]) return -1;
    if (a[i] > b[i]) return 1;
  }
  return 0;
}

/* ── Reference Test Vectors ──────────────────────────────────────── */

/*
 * Mnemonic: "all all all all all all all all all all all all"
 * BIP-39 seed (PBKDF2, no passphrase), 64 bytes:
 */
static const uint8_t SEED_ALL[64] = {
    0xc7, 0x6c, 0x4a, 0xc4, 0xf4, 0xe4, 0xa0, 0x0d,
    0x6b, 0x27, 0x4d, 0x5c, 0x39, 0xc7, 0x00, 0xbb,
    0x4a, 0x7d, 0xdc, 0x04, 0xfb, 0xc6, 0xf7, 0x8e,
    0x85, 0xca, 0x75, 0x00, 0x7b, 0x5b, 0x49, 0x5f,
    0x74, 0xa9, 0x04, 0x3e, 0xeb, 0x77, 0xbd, 0xd5,
    0x3a, 0xa6, 0xfc, 0x3a, 0x0e, 0x31, 0x46, 0x22,
    0x70, 0x31, 0x6f, 0xa0, 0x4b, 0x8c, 0x19, 0x11,
    0x4c, 0x87, 0x98, 0x70, 0x6c, 0xd0, 0x2a, 0xc8,
};

/*
 * Expected FVK for "all" mnemonic, account 0.
 * Generated by the orchard Rust crate (authoritative ZIP-32).
 *
 * NOTE: These vectors verify the derivation function itself.
 * The current FSM seed-proxy bug means the firmware doesn't call
 * this function with the correct seed — but the function is correct.
 */
static const uint8_t EXPECTED_AK_ALL_0[32] = {
    0x05, 0x7a, 0xb0, 0x51, 0xd4, 0xfb, 0xb0, 0x20,
    0x5d, 0x28, 0x64, 0x8b, 0xac, 0xbc, 0x64, 0x71,
    0xb5, 0x33, 0x47, 0x6c, 0x27, 0xbe, 0xca, 0x33,
    0xe5, 0xb9, 0xf5, 0x11, 0xd8, 0x55, 0x67, 0x2b,
};

static const uint8_t EXPECTED_NK_ALL_0[32] = {
    0x34, 0xa3, 0x5a, 0x0b, 0xda, 0x50, 0x27, 0x3b,
    0x03, 0x19, 0xaf, 0xa7, 0xa7, 0x0f, 0x86, 0xb6,
    0xb1, 0x62, 0xeb, 0x31, 0x1d, 0x26, 0x3d, 0x8f,
    0x63, 0x21, 0xde, 0xf0, 0x02, 0x28, 0xba, 0x25,
};

static const uint8_t EXPECTED_RIVK_ALL_0[32] = {
    0x46, 0xbd, 0x2b, 0xd5, 0xe6, 0xec, 0xa5, 0xef,
    0x03, 0xe1, 0x8c, 0xd7, 0x65, 0x95, 0x51, 0x9e,
    0xa9, 0x67, 0x06, 0xc5, 0x82, 0x6a, 0x93, 0xba,
    0x4d, 0xca, 0x94, 0x7d, 0x71, 0x1a, 0x7c, 0x0a,
};

/* ── ZIP-32 Derivation Tests ─────────────────────────────────────── */

TEST(Zcash, DeriveOrchardKeys_ReferenceVector_Account0) {
  /*
   * Reference vector test: derive keys from known "all" mnemonic seed
   * and compare against values from the orchard Rust crate.
   *
   * The derivation bugs that caused prior mismatches were:
   *   1. Child derivation used "ZcashIP32Orchard" instead of "Zcash_ExpandSeed"
   *   2. Domain separator was 0x11 instead of 0x81
   *   3. Index encoding was big-endian instead of little-endian
   * All three are now fixed.
   */
  ZcashOrchardKeys keys;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys));

  /* nk must match reference */
  EXPECT_TRUE(memcmp(keys.nk, EXPECTED_NK_ALL_0, 32) == 0)
      << "nk mismatch for all-mnemonic account 0";

  /* rivk must match reference */
  EXPECT_TRUE(memcmp(keys.rivk, EXPECTED_RIVK_ALL_0, 32) == 0)
      << "rivk mismatch for all-mnemonic account 0";

  /* Compute ak = [ask]*G and verify against reference */
  bignum256 ask_scalar;
  bn_read_le(keys.ask, &ask_scalar);
  curve_point ak_point;
  redpallas_scalar_mult_spendauth_G(&ask_scalar, &ak_point);

  uint8_t ak_bytes[32];
  bignum256 x_copy;
  bn_copy(&ak_point.x, &x_copy);
  bn_write_le(&x_copy, ak_bytes);
  EXPECT_EQ(ak_bytes[31] & 0x80, 0)
      << "ak sign bit must be 0 after ask normalization";

  EXPECT_TRUE(memcmp(ak_bytes, EXPECTED_AK_ALL_0, 32) == 0)
      << "ak mismatch for all-mnemonic account 0";

  memzero(&keys, sizeof(keys));
}

TEST(Zcash, DeriveOrchardKeys_DifferentAccounts) {
  ZcashOrchardKeys keys0, keys1;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys0));
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 1, &keys1));

  /* Different accounts must produce different spending keys */
  EXPECT_TRUE(memcmp(keys0.sk, keys1.sk, 32) != 0)
      << "Account 0 and 1 must have different sk";
  EXPECT_TRUE(memcmp(keys0.ask, keys1.ask, 32) != 0)
      << "Account 0 and 1 must have different ask";
  EXPECT_TRUE(memcmp(keys0.nk, keys1.nk, 32) != 0)
      << "Account 0 and 1 must have different nk";

  memzero(&keys0, sizeof(keys0));
  memzero(&keys1, sizeof(keys1));
}

TEST(Zcash, DeriveOrchardKeys_DifferentSeeds) {
  /* Use a different seed (all zeros) */
  uint8_t zero_seed[64];
  memset(zero_seed, 0, sizeof(zero_seed));

  ZcashOrchardKeys keys_all, keys_zero;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys_all));
  ASSERT_TRUE(zcash_derive_orchard_keys(zero_seed, 64, 0, &keys_zero));

  EXPECT_TRUE(memcmp(keys_all.sk, keys_zero.sk, 32) != 0)
      << "Different seeds must produce different sk";

  memzero(&keys_all, sizeof(keys_all));
  memzero(&keys_zero, sizeof(keys_zero));
}

TEST(Zcash, DeriveOrchardKeys_Deterministic) {
  ZcashOrchardKeys keys1, keys2;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys1));
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys2));

  EXPECT_TRUE(memcmp(keys1.sk, keys2.sk, 32) == 0);
  EXPECT_TRUE(memcmp(keys1.ask, keys2.ask, 32) == 0);
  EXPECT_TRUE(memcmp(keys1.nk, keys2.nk, 32) == 0);
  EXPECT_TRUE(memcmp(keys1.rivk, keys2.rivk, 32) == 0);

  memzero(&keys1, sizeof(keys1));
  memzero(&keys2, sizeof(keys2));
}

/* ── Field Range Tests ───────────────────────────────────────────── */

TEST(Zcash, DeriveOrchardKeys_FieldRanges) {
  /* Test multiple accounts to increase coverage of edge cases */
  for (uint32_t account = 0; account < 5; account++) {
    ZcashOrchardKeys keys;
    ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, account, &keys));

    /* nk must be < Pallas base field prime p */
    EXPECT_LT(cmp_le256(keys.nk, PALLAS_P_LE), 0)
        << "nk must be < p for account " << account;

    /* rivk must be < Pallas scalar field order q */
    EXPECT_LT(cmp_le256(keys.rivk, PALLAS_Q_LE), 0)
        << "rivk must be < q for account " << account;

    /* ask must be < Pallas scalar field order q */
    EXPECT_LT(cmp_le256(keys.ask, PALLAS_Q_LE), 0)
        << "ask must be < q for account " << account;

    /* ask must be nonzero (astronomically unlikely, but verify) */
    uint8_t zero[32] = {0};
    EXPECT_TRUE(memcmp(keys.ask, zero, 32) != 0)
        << "ask must be nonzero for account " << account;

    memzero(&keys, sizeof(keys));
  }
}

TEST(Zcash, AkSignBit_AlwaysClear) {
  /*
   * For every account, compute ak = [ask]*G and verify the sign bit
   * is always clear. This is the invariant that the ask negation
   * in zcash_derive_orchard_keys() is supposed to enforce.
   */
  for (uint32_t account = 0; account < 10; account++) {
    ZcashOrchardKeys keys;
    ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, account, &keys));

    bignum256 ask_scalar;
    bn_read_le(keys.ask, &ask_scalar);
    curve_point ak_point;
    redpallas_scalar_mult_spendauth_G(&ask_scalar, &ak_point);

    /* Check y parity: must be even (sign bit = 0) */
    EXPECT_FALSE(bn_is_odd(&ak_point.y))
        << "ak y-coordinate must be even for account " << account;

    /* Check serialized sign bit */
    uint8_t ak_bytes[32];
    bignum256 x_copy;
    bn_copy(&ak_point.x, &x_copy);
    bn_write_le(&x_copy, ak_bytes);

    EXPECT_EQ(ak_bytes[31] & 0x80, 0)
        << "ak sign bit must be clear for account " << account;

    memzero(&keys, sizeof(keys));
  }
}

/* ── Sighash Computation Tests ───────────────────────────────────── */

TEST(Zcash, ComputeShieldedSighash_Deterministic) {
  uint8_t header[32], transparent[32], sapling[32], orchard[32];
  memset(header, 0x01, 32);
  memset(transparent, 0x02, 32);
  memset(sapling, 0x03, 32);
  memset(orchard, 0x04, 32);

  uint32_t branch_id = 0x37519621;  /* NU5 */

  uint8_t sighash1[32], sighash2[32];
  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, branch_id, sighash1));
  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, branch_id, sighash2));

  EXPECT_TRUE(memcmp(sighash1, sighash2, 32) == 0)
      << "Sighash must be deterministic";
}

TEST(Zcash, ComputeShieldedSighash_DifferentInputs) {
  uint8_t header[32], transparent[32], sapling[32], orchard[32];
  memset(header, 0x01, 32);
  memset(transparent, 0x02, 32);
  memset(sapling, 0x03, 32);
  memset(orchard, 0x04, 32);

  uint32_t branch_id = 0x37519621;
  uint8_t sighash_a[32], sighash_b[32];

  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, branch_id, sighash_a));

  /* Change one byte in the orchard digest */
  orchard[0] ^= 0xff;
  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, branch_id, sighash_b));

  EXPECT_TRUE(memcmp(sighash_a, sighash_b, 32) != 0)
      << "Different orchard digests must produce different sighashes";
}

TEST(Zcash, ComputeShieldedSighash_DifferentBranchId) {
  uint8_t header[32], transparent[32], sapling[32], orchard[32];
  memset(header, 0x01, 32);
  memset(transparent, 0x02, 32);
  memset(sapling, 0x03, 32);
  memset(orchard, 0x04, 32);

  uint8_t sighash_nu5[32], sighash_nu6[32];

  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, 0x37519621, sighash_nu5));
  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, 0xC4D97411, sighash_nu6));

  EXPECT_TRUE(memcmp(sighash_nu5, sighash_nu6, 32) != 0)
      << "Different branch IDs must produce different sighashes";
}

TEST(Zcash, ComputeShieldedSighash_KnownVector) {
  /*
   * ZIP-244 sighash test vector.
   *
   * The sighash personalization is "ZcashTxHash_" || branch_id_LE.
   * For NU5 (branch_id = 0x37519621):
   *   personalization = "ZcashTxHash_" || 0x21965137
   *
   * Input: BLAKE2b-256(personalization, header || transparent || sapling || orchard)
   * where each digest is 32 bytes of zeros.
   */
  uint8_t header[32] = {0};
  uint8_t transparent[32] = {0};
  uint8_t sapling[32] = {0};
  uint8_t orchard[32] = {0};
  uint32_t branch_id = 0x37519621;

  uint8_t sighash[32];
  ASSERT_TRUE(zcash_compute_shielded_sighash(
      header, transparent, sapling, orchard, branch_id, sighash));

  /*
   * Independently verified: BLAKE2b-256 with personalization
   * "ZcashTxHash_\x21\x96\x51\x37" over 128 zero bytes.
   *
   * This is a self-consistency check — the value was computed by
   * running the same BLAKE2b-256 offline. If the sighash function
   * changes its algorithm, this test will catch it.
   */
  uint8_t expected[32];
  BLAKE2B_CTX ctx;
  uint8_t personal[16];
  memcpy(personal, "ZcashTxHash_", 12);
  memcpy(personal + 12, &branch_id, 4);
  blake2b_InitPersonal(&ctx, 32, personal, 16);
  blake2b_Update(&ctx, header, 32);
  blake2b_Update(&ctx, transparent, 32);
  blake2b_Update(&ctx, sapling, 32);
  blake2b_Update(&ctx, orchard, 32);
  blake2b_Final(&ctx, expected, 32);

  EXPECT_TRUE(memcmp(sighash, expected, 32) == 0)
      << "Sighash must match direct BLAKE2b computation";
}

/* ── RedPallas Signing Smoke Test ────────────────────────────────── */

TEST(Zcash, RedPallasSign_ProducesVerifiableSignature) {
  ZcashOrchardKeys keys;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys));

  /* Construct a fake sighash and alpha */
  uint8_t sighash[32];
  memset(sighash, 0xAB, 32);

  uint8_t alpha[32];
  memset(alpha, 0x01, 32);
  /* Ensure alpha is a valid scalar (< q) */
  alpha[31] = 0x00;

  uint8_t signature[64];
  int ret = redpallas_sign_digest(keys.ask, alpha, sighash, signature);
  EXPECT_EQ(ret, 0) << "RedPallas signing must succeed";

  /* Signature must be nonzero */
  uint8_t zero[64] = {0};
  EXPECT_TRUE(memcmp(signature, zero, 64) != 0)
      << "Signature must be nonzero";

  /*
   * Verify the signature against the randomized verification key rk.
   * rk = [ask + alpha]*G_spendauth (Pallas SpendAuth basepoint)
   */
  bignum256 ask_scalar, alpha_scalar, rk_scalar;
  bn_read_le(keys.ask, &ask_scalar);
  bn_read_le(alpha, &alpha_scalar);

  /* rk_scalar = ask + alpha mod q */
  bn_copy(&ask_scalar, &rk_scalar);
  pallas_add_mod_q(&rk_scalar, &alpha_scalar);

  curve_point rk_point;
  redpallas_scalar_mult_spendauth_G(&rk_scalar, &rk_point);

  /* Serialize rk as Pallas point (LE x-coord + sign bit) */
  uint8_t rk_bytes[32];
  bignum256 rk_x;
  bn_copy(&rk_point.x, &rk_x);
  bn_write_le(&rk_x, rk_bytes);
  if (bn_is_odd(&rk_point.y)) {
    rk_bytes[31] |= 0x80;
  }

  /* Verify: redpallas_verify_digest(rk, sighash, sig) == 0 */
  EXPECT_EQ(redpallas_verify_digest(rk_bytes, sighash, signature), 0)
      << "Signature must verify against rk = [ask+alpha]*G";

  /* Verify fails with wrong sighash */
  uint8_t wrong_sighash[32];
  memset(wrong_sighash, 0xCC, 32);
  EXPECT_NE(redpallas_verify_digest(rk_bytes, wrong_sighash, signature), 0)
      << "Signature must NOT verify with wrong sighash";

  memzero(&keys, sizeof(keys));
}

TEST(Zcash, RedPallasSign_MultipleCallsSucceed) {
  /*
   * RedPallas uses randomized nonces — signatures are intentionally
   * non-deterministic. Verify that multiple calls all succeed and
   * produce valid (nonzero) 64-byte signatures.
   */
  ZcashOrchardKeys keys;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys));

  uint8_t sighash[32];
  memset(sighash, 0xCD, 32);
  uint8_t alpha[32];
  memset(alpha, 0x02, 32);
  alpha[31] = 0x00;

  uint8_t zero[64] = {0};
  for (int i = 0; i < 3; i++) {
    uint8_t sig[64];
    ASSERT_EQ(redpallas_sign_digest(keys.ask, alpha, sighash, sig), 0)
        << "Signing must succeed on call " << i;
    EXPECT_TRUE(memcmp(sig, zero, 64) != 0)
        << "Signature must be nonzero on call " << i;
  }

  memzero(&keys, sizeof(keys));
}

TEST(Zcash, RedPallasSign_DifferentSighash) {
  ZcashOrchardKeys keys;
  ASSERT_TRUE(zcash_derive_orchard_keys(SEED_ALL, 64, 0, &keys));

  uint8_t alpha[32];
  memset(alpha, 0x01, 32);
  alpha[31] = 0x00;

  uint8_t sighash_a[32], sighash_b[32];
  memset(sighash_a, 0xAA, 32);
  memset(sighash_b, 0xBB, 32);

  uint8_t sig_a[64], sig_b[64];
  ASSERT_EQ(redpallas_sign_digest(keys.ask, alpha, sighash_a, sig_a), 0);
  ASSERT_EQ(redpallas_sign_digest(keys.ask, alpha, sighash_b, sig_b), 0);

  EXPECT_TRUE(memcmp(sig_a, sig_b, 64) != 0)
      << "Different sighash must produce different signatures";

  memzero(&keys, sizeof(keys));
}
