services:
  kkemu:
    image: kktech/kkemu-bitcoin-only:latest
    build:
      args:
        coinsupport: "-DKK_BITCOIN_ONLY=ON"

  firmware-unit:
    build:
      args:
        coinsupport: "-DKK_BITCOIN_ONLY=ON"

  python-keepkey:
    environment:
      KK_FIRMWARE_VARIANT: bitcoin-only
