from SCons.Script import *
from scons_util import *

Import('env')
init_project(env, deps=['app', 
                        'crypto', 
                        'foundation', 
                        'client', 
                        'bitcoin',
                        'trezor-bitcoin',
                        'graphics_engine'])

