from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Dependencies
#
deps = ['interface', 'nanopb', 'keepkey_board', 'crypto']
project_deps += deps

#
# Debug Link
#
if int(ARGUMENTS.get('debug_link', 0)):
    env = add_flags(env, ['-DDEBUG_LINK=1'])
else:
    env = add_flags(env, ['-DDEBUG_LINK=0'])

#
# Memory Protection
#
if int(ARGUMENTS.get('memory_protect', 0)):
    env = add_flags(env, ['-DMEMORY_PROTECT=1'])
else:
    env = add_flags(env, ['-DMEMORY_PROTECT=0'])

# Build ID
if int(ARGUMENTS.get('build_id', 0)):
    env = add_flags(env, ['-DBUILD_ID=%s' % (ARGUMENTS.get('build_id', 0))])

init_project(env, deps=deps, libs=['opencm3_stm32f2'])