from SCons.Script import *
from scons_util import *

Import('env', 'project_deps')

#
# Dependencies
#
deps = ['interface', 'nanopb', 'keepkey_board', 'crypto']
project_deps += deps

init_project(env, 
    deps=deps, 
    libs=['opencm3_stm32f2'])