from SCons.Script import *
from scons_util import *

Import('env')
init_project(env, deps=['client',
                        'crypto',
                        'foundation',
                        'trezor-bitcoin'])

